[build-system]
# Version 59 is the last to support Python 3.6.
requires = ["setuptools>=59.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 105
py36 = true
skip-string-normalization = true
